using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// Particles to be generated by the beam on mirror collision;

public class LaserParticles : MonoBehaviour
{
	private ParticleSystem parSystem;

	// Hello there!
	void Start() {
		parSystem = GetComponent<ParticleSystem>();
	}

	public void Subscribe2Parent(LaserBeam parentBeam) {
		parentBeam.OnBeamEnd += LaserParticles_OnBeamEnd;
	}

	private void LaserParticles_OnBeamEnd() {
		var emission = parSystem.emission;
		emission.enabled = false;
		Destroy(gameObject, 0.25f);
	}
}