using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// Particles to be generated by the beam on mirror collision;

public class LaserParticles : MonoBehaviour
{
	private float lifetime;
	private ParticleSystem parSystem;

	// Hello there!
	void Start() {
		parSystem = GetComponent<ParticleSystem>();
	}

	// Disable emissions when it runs out of life time;
	void Update() {
		lifetime -= Time.deltaTime;
		if (lifetime <= 0.5f) {
			var emission = parSystem.emission;
			emission.enabled = false;
			Destroy(gameObject, 1f);
		}
	}

	public void SetLife(float lifetime) {
		this.lifetime = lifetime;
	}
}