using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// Particles to be generated by the beam on mirror collision;

public class LaserParticles : MonoBehaviour
{
	// Duration of the object;
	public float life;

	// References to the particle system component;
	private ParticleSystem parSystem;
	private ParticleSystem.EmissionModule _emissions;

	// Set references;
	void Start() {
		parSystem = GetComponent<ParticleSystem>();
		_emissions = parSystem.emission;
	}

	// Disable emissions when it runs out of life time;
	void Update() {
		life -= Time.deltaTime;
		if (life <= 0.5f) {
			_emissions.enabled = false;
			Destroy(gameObject, 1f);
		}
	}
}